# Generated by Django 4.2.9 on 2024-02-17 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('description', models.TextField(default='No description provided')),
                ('watering_interval', models.IntegerField(help_text='Days between watering')),
                ('light_requirements', models.CharField(default='Unknown Light Requirements', max_length=100)),
                ('last_watered', models.DateField(auto_now_add=True)),
                ('fertilization_interval', models.IntegerField(help_text='Days between fertilization')),
                ('last_fertilized', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(default='plant_images/default_plant.jpg', upload_to='plant_images')),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('WATER', 'Water'), ('FERTILIZE', 'Fertilize')], max_length=20)),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant')),
            ],
        ),
    ]
