# Generated by Django 4.2.9 on 2024-04-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_plant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='last_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
