# Generated by Django 4.2 on 2024-08-19 10:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_todo_last_completed_alter_todo_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='last_completed',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='task_type',
        ),
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='todo_type',
            field=models.CharField(choices=[('watering', 'Watering'), ('fertilization', 'Fertilization')], default='watering', max_length=20),
        ),
        migrations.AddField(
            model_name='todo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='plants.plant'),
        ),
    ]
